#!/bin/bash

KERNEL_RELEASE=`dir -1rt /usr/src/kernels/ | tail -1`
echo Patching $KERNEL_RELEASE
cd /usr/src/kernels/$KERNEL_RELEASE/include/drm
ln -s /usr/include/drm/drm.h drm.h
ln -s /usr/include/drm/drm_sarea.h drm_sarea.h
ln -s /usr/include/drm/drm_mode.h drm_mode.h
ln -s /usr/include/drm/drm_fourcc.h drm_fourcc.h